### ISSUE TITLE
CARGO_TARGET_DIR not respected

### ISSUE THREAD

**Issue by alula** [rust-windowing/android-ndk-rs#102]
I'm using a separate CARGO_TARGET_DIR for Android builds so tooling doesn't conflict, however `cargo apk` doesn't seem to respect that and tries to use default target directory:

```
warning: 53 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 57.33s
Error: Path "/path/to/my/project/target/aarch64-linux-android/debug/libengine.so" doesn't exist.
```

**Comment by MarijnS95** [comment]
@alula This should be fixed by https://github.com/dvc94ch/cargo-subcommand/pull/4. Would you mind testing it?

**Comment by GuilhermeWerner** [comment]
Very good to have found this issue, I was almost opening one. I suffered a lot because of that.

I will test this version right now. Tanks :+1:

**Comment by GuilhermeWerner** [comment]
Unfortunately it seems that the error still persists.

I forked the cargo-apk and changed the version of the cargo-subcommand to the latest one and the same error still happens.

```
Guilherme in Engine/Game on  mobile [!?] ➜ cargo apk run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
Error: No such file or directory (os error 2)
```
A printscreen of my project.

![Captura de tela de 2021-01-22 07-49-44_cut](https://user-images.githubusercontent.com/26710260/105482458-279ef000-5c87-11eb-9316-8587c4156c1c.png)

I also test on winit project, and after change the target-dir i got the same error.

**Comment by MarijnS95** [comment]
@GuilhermeWerner Sorry to hear that.

The easiest way to test the latest version is now just `cargo install --force cargo-apk` as `cargo-subcommand` has already been published. Note that https://github.com/dvc94ch/cargo-subcommand/pull/4 introduced a regression that has been dealt with in https://github.com/dvc94ch/cargo-subcommand/pull/5.

Otherwise all we can do is inject some debug statements in `cargo-subcommand`; at some point we should re-wrap file-related expressions with the path that caused it.

**Comment by GuilhermeWerner** [comment]
I find the error. It is hard coded in that part of the cargo-subcommand.

He is creating the "target" folder at the root of the workspace. To fix it, just use the target-dir option in the cargo configuration file

![Captura de tela de 2021-01-22 08-53-05_cut](https://user-images.githubusercontent.com/26710260/105487833-7badd280-5c8f-11eb-8f64-07687db9b6f5.png)

I switched to Binaries to test in my project and it went well.

**Comment by MarijnS95** [comment]
@GuilhermeWerner that sits inside `target_dir.unwrap_or_else`, where `target_dir` is assigned with the value of `CARGO_TARGET_DIR` as per the title of this issue.

Indeed, `cargo-dir` in `Cargo.toml` is not supported yet, but should be trivial to add. Feel free to open a PR :rocket:

**Comment by GuilhermeWerner** [comment]
This cargo configuration in defined in .cargo/config.toml:

```
[build]
target-dir = "target"
```

https://doc.rust-lang.org/cargo/reference/config.html

**Comment by dvc94ch** [comment]
It is somewhat difficult to be compatible with cargo in every way. If you open a PR we can make cargo-subcommand more compatible for all cargo-subcommand users

**Comment by GuilhermeWerner** [comment]
I just implemented the fix, soon I will open the PR in cargo-subcommand
